### ISSUE TITLE
error indexOF undefined

### ISSUE THREAD

**Issue by fynnit** [n8henrie/homebridge-rcswitch-gpiomem#7] opened 2016-11-01 22:08 UTC
dear henrie, big props to this amazing plugin. i almost got it to work, even sniffed out the codes, but after adding them to my config.json, and reloading homebrige, i got this error.

do you know how to fix it? im a rookie in the pi business! 

cheers and thank you! 

fynn
```
[11/1/2016, 10:59:36 PM] [Switch A] Initializing RCSwitch accessory...
[11/1/2016, 10:59:36 PM] [Switch B] Initializing RCSwitch accessory...
[11/1/2016, 10:59:36 PM] [Switch C] Initializing RCSwitch accessory...
[11/1/2016, 10:59:36 PM] [Switch D] Initializing RCSwitch accessory...
/usr/local/lib/node_modules/homebridge/lib/api.js:46
  if (name.indexOf('.') == -1) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
```

**Comment by fynnit** [comment] 2016-11-01 22:09
and the config.json part:

``` json
},  {
                "accessory": "RCSwitch",
                "name": "Switch A",
                "onCode": 5359777,
                "offCode": 5353887,
                "pulseLength": 329,
                "bitLength": 24,
            "repeats": 10
        },{
        "accessory": "RCSwitch",
                "name": "Switch B",
                "onCode": 5352849,
                "offCode": 5352852,
                "pulseLength": 329,
                "bitLength": 24,
                "repeats": 10
        },{
        "accessory": "RCSwitch",
                "name": "Switch C",
                "onCode": 5353617,
                "offCode": 5353620,
                "pulseLength": 329,
                "bitLength": 24,
                "repeats": 10
        },{
        "accessory": "RCSwitch",
                "name": "Switch D",
                "onCode": 5353809,
                "offCode": 5353812,
                "pulseLength": 329,
                "bitLength": 24,
                "repeats": 10
        },{ 
```

**Comment by n8henrie** [comment] 2016-11-05 06:54
Huh. Sorry for the slow reply. What version of homebridge and
homebridge-rcswitch-gpiomem are you running? I'll see if I can replicate.
Also are you sure about the pulse length of 329?

Nate

**Comment by mefynn** [comment] 2016-11-06 11:35
hey nate! thanks for the reply.
i managed to fix this bug. it was caused by a misconfiguration of another accessory.
but i still cant use ur plugin. ive been trying to send signals with your rf_pi, but nothing goes through.
ive connected the *send* module to 2 (vcc) 6 (grd) and 11 (out - atad)
the *receive* module is hooked up to 4 (vcc) 9(grd) and 13 (in - data)
is it possible to connect both modules or is this where my error origins?

fynn

**Comment by fynnit** [comment] 2016-11-06 11:40
thanks nate for your reply. the original error was due to a misconfig.
i take it has to be the exact puls length? what if i have a different length on the out frequence? 

fynn

**Comment by fynnit** [comment] 2016-11-06 11:49
ur right. the puls length was incorrect. extraordinary work nate! you made my year!

**Comment by n8henrie** [comment] 2016-11-09 05:50
Sweet! Glad you got it working. If there's nothing else, would you mind closing the issue?

**Closed as completed** 2016-11-09 15:55 UTC
